name: environment
description: "environment Flutter project."
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  riverpod_generator: ^2.4.0

flutter: