name: mvvm
description: "MVVM Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  serverpod_flutter: 1.2.6
  sample_client:
    path: ../../server/sample/sample_client
  hooks_riverpod: ^2.5.1
  go_router: ^13.2.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
