name: device_info
description: "device_info Flutter project."
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter

dev_dependencies:

flutter: